#define ProductKind "t1"
#define SetupAppId "{{EEED30B5-36C5-4BED-B344-41FA0A38FF6D}"
#define AppName "T1遥控器桥接"
#define ProductId "T1RemoteBridge"
#define AppFolder "T1RemoteBridge"
#define AppExeName "T1RemoteBridge.exe"
#define OutputBaseFilename "T1RemoteBridgeSetup"
#define ReadmeFile "readme-t1.txt"
#define EndpointPattern "(?i)Mic Device"
#include "StandaloneBridgeSetup.common.iss"
