#define ProductKind "xiaomi"
#define SetupAppId "{{C87B7439-E849-47B9-A3AC-B35AC7986CE4}"
#define AppName "MiVibe Remote"
#define ProductId "MiVibeRemote"
#define AppFolder "MiVibe Remote"
#define AppExeName "MiVibeRemote.exe"
#define OutputBaseFilename "MiVibeRemoteSetup"
#define AppPublisher "MiVibe Remote Contributors"
#define AppGroupName "MiVibe Remote"
#define ReadmeFile "readme-xiaomi.txt"
#define EndpointPattern "CABLE Output"
#include "StandaloneBridgeSetup.common.iss"
